Repository achilleasmitos/text-adventure, pull requests merged in 2023-04, with the labels that each got.

#6 Added handle_sound utils function
  .vscode/tasks.json
  main.cpp
  resources/music/boss_battle.mp3
  resources/music/exploration.mp3
  utils.h
Labels: enhancement

#9 Text_adventure_menu
  .vscode/settings.json
  main.cpp
  start_menu.h
  utils.h
Labels: enhancement

#11 Fixed include headers and building of cpp files
  .vscode/tasks.json
  creature/main_character/main_character.h
  main.cpp
  start_menu/start_menu.cpp
  start_menu/start_menu.h
  utils.cpp
  utils.h
Labels: bug

#17 changed folder structure
  .vscode/tasks.json
  src/creature/creature.cpp
  src/creature/creature.h
  src/creature/main_character/main_character.cpp
  src/creature/main_character/main_character.h
  src/main.cpp
  src/resources/music/boss_battle.mp3
  src/resources/music/exploration.mp3
  src/start_menu/start_menu.cpp
  src/start_menu/start_menu.h
  src/utils/utils.cpp
  src/utils/utils.h
Labels: tec story

#27 added a loading screen
  .vscode/tasks.json
  src/loading_screen/loading_screen.cpp
  src/loading_screen/loading_screen.h
  src/main.cpp
  src/start_menu/start_menu.cpp
Labels: enhancement
